# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
permalink: 			 /:year/:month/:day/:title
relative_permalinks: true

# Setup
title:               'On the Road, Walk hard! 在路上，永不止步！'
tagline:             ''
description:         "这是一个纯静态的文章留存地址，主要记录技术文章。."
url:                 http://im.onrd.net
baseurl:             /
paginate:            20

#git setting
github:
  repo: 			https://github.com/maskkid

#other links
links:
  blog: 			http://blog.onrd.net

# About/contact
author:
  name:              SIMO
  url:               https://im.onrd.net
  email:             im@onrd.net

# Custom vars
version:             1.0.0
