# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
permalink: 			 /:year/:month/:day/:title
relative_permalinks: true

# Setup
title:               'On the Road, Walk hard!'
tagline:             ''
description:         "This is my clean env, most about my work n study."
url:                 http://im.onrd.net
baseurl:             /
paginate:            5

#git setting
github:
  repo: 			https://github.com/maskkid

# About/contact
author:
  name:              SIMO
  url:               https://im.onrd.net
  email:             im@onrd.net

# Custom vars
version:             1.0.0
